global_exclude_dirs:
    - test/fixtures

rules:
    php.use_exit_function:
        enabled: true
            ignore_files:
                - php5to7.php
    php.dynamically_change_configuration:
        enabled: true
            ignore_files:
                - php5to7.php
